"""Detection signals for Provenance Guard.

Two genuinely distinct signals (see planning.md §2):
  - Signal 1: LLM classifier (Groq)  -> semantic / holistic judgment   (Milestone 3)
  - Signal 2: Stylometric heuristics -> structural statistics          (Milestone 4)

Each signal returns a dict with at least an `ai_score` in [0, 1] = estimated P(AI).
"""

import json
import os

from groq import Groq

LLM_MODEL = "llama-3.3-70b-versatile"

# A single shared client. Reads GROQ_API_KEY from the environment (loaded via dotenv in app.py).
_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


# --------------------------------------------------------------------------- #
# Signal 1 — LLM classifier (semantic)
# --------------------------------------------------------------------------- #

_LLM_SYSTEM_PROMPT = """You are an expert text-forensics analyst for a creative writing \
platform. You estimate how likely a piece of text was generated by an AI language model \
rather than written by a human.

Judge holistically on signals such as: generic-but-fluent phrasing, even hedging \
("it is important to note"), balanced both-sides framing, low risk-taking, uniform smooth \
transitions, and a lack of idiosyncratic human voice. Human writing tends to be more \
irregular, opinionated, specific, and occasionally messy.

Important fairness rule: formal, careful, or non-native-English writing is NOT by itself \
evidence of AI. Do not over-penalize it.

Respond with ONLY a JSON object, no prose, in exactly this shape:
{"ai_score": <float 0.0-1.0>, "rationale": "<one short sentence>"}
where ai_score is your estimated probability the text is AI-generated \
(0.0 = clearly human, 1.0 = clearly AI)."""


def llm_signal(text):
    """Signal 1: ask Groq how likely the text is AI-generated.

    Returns {"ai_score": float in [0,1], "rationale": str, "ok": bool}.
    On any failure the signal degrades gracefully to a maximally-uncertain 0.5
    with ok=False, so the scorer can lower overall confidence (planning.md §2).
    """
    try:
        resp = _get_client().chat.completions.create(
            model=LLM_MODEL,
            temperature=0,  # determinism
            max_tokens=200,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _LLM_SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
        score = float(data.get("ai_score"))
        score = max(0.0, min(1.0, score))  # clamp into [0,1]
        rationale = str(data.get("rationale", "")).strip()
        return {"ai_score": score, "rationale": rationale, "ok": True}
    except Exception as exc:  # network error, bad JSON, missing key, etc.
        return {
            "ai_score": 0.5,
            "rationale": f"LLM signal unavailable ({type(exc).__name__}); defaulting to uncertain.",
            "ok": False,
        }
